# Copyright 2020 YourBase Inc.
# SPDX-License-Identifier: BSD-3-Clause

dependencies:
  build:
    - go:1.15

build_targets:
  - name: default
    commands:
      - go mod download
      - go test -race ./...

ci:
  builds:
    - name: test
      build_target: default
      when: branch is 'main' OR action is 'pull_request'
